apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-development
spec:
  replicas: 3
  selector: 
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: juniorbezerra01/multi-client-10-40
          ports:
            - containerPort: 3000